### PR TITLE
CMake build support

### PR DESCRIPTION
**Pull request by hummeltech**
This adds `CMake` build system support to `mod_tile`.

* Integrated `mod_tile.so` tests from `GitHub Actions` into `CMake/CTest` configuration
  * Also added some more tests
    * A test for `/dirty` and `/status`
    * A run of `render_speedtest` with `--max-zoom=10`
  * They can now easily be run locally with `ctest`:
    ```shell
    $ ctest -T test
     Test project /__w/mod_tile/mod_tile/build
          Start  1: gen_tile_test
     1/12 Test  #1: gen_tile_test ....................   Passed    4.90 sec
          Start  2: create_dirs
     2/12 Test  #2: create_dirs ......................   Passed    0.00 sec
          Start  3: start_renderd
     3/12 Test  #3: start_renderd ....................   Passed    0.08 sec
          Start  4: start_httpd
     4/12 Test  #4: start_httpd ......................   Passed    0.04 sec
          Start  5: render_speedtest
     5/12 Test  #5: render_speedtest .................   Passed    8.81 sec
          Start  6: download_tile
     6/12 Test  #6: download_tile ....................   Passed    0.25 sec
          Start  7: check_tile
     7/12 Test  #7: check_tile .......................   Passed    0.03 sec
          Start  8: dirty_tile
     8/12 Test  #8: dirty_tile .......................   Passed    6.07 sec
          Start  9: remove_tile
     9/12 Test  #9: remove_tile ......................   Passed    0.00 sec
          Start 10: stop_renderd
    10/12 Test #10: stop_renderd .....................   Passed    0.03 sec
          Start 11: stop_httpd
    11/12 Test #11: stop_httpd .......................   Passed    0.01 sec
          Start 12: clear_dirs
    12/12 Test #12: clear_dirs .......................   Passed    0.01 sec
    
    100% tests passed, 0 tests failed out of 12
    
    Total Test time (real) =  20.25 sec
    ```
* Coverage is now also supported when using `CMake/CTest` & `gcc/g++`
  * It can also easily be run locally with `ctest` (when built with `CFLAGS/CXXFLAGS=--coverage`):
    ```shell
    $ ctest -T coverage
     Performing coverage
       Processing coverage (each . represents one file):
        .................................................. processed: 50 out of 83
        .................................
       Accumulating results (each . represents one file):
        .........................
	    Covered LOC:         3317
	    Not covered LOC:     6836
	    Total LOC:           10153
	    Percentage Coverage: 32.67%
    ```

### CODE REVIEW

**Comment by hummeltech** [comment]
@xamanu Alright, I've been working towards making this pull request easier to review. Let me know if this helps. If so, I can rebase #288 as well.

* I think I've moved out everything I could from this pull request:
  * #296
  * #298
  * #299
* Except for this pull request (it's referenced in both pull requests):
  * #297

**Comment by xamanu** [comment]
Hi @hummeltech, thank you very much for keeping this software development active and for your patience (i have been running behind reviewing quite a lot)! I reviewed and merged all of the split-out PRs. It would be nice if you could rebase on newest `master` and let me know, when this good one is ready for review. Thanks!

**Comment by hummeltech** [comment]
Alright @xamanu, I've taken care of rebasing this branch, I'll work on getting the "testing/documentation" pull request (#288) in good shape.

**Comment by xamanu** [comment]
Wonderful. Thanks a lot!

**Pull request merged**
