### PR TITLE
Make `/status` and `/dirty` URLs controlable with apache conf (& default disable)

### PR DESCRIPTION
**Pull request by amandasaurus**
This patch makes the `/status` & `/dirty` URL requests diabled by default, and allows one to turn it on or off with `ModTileStatusURL On`/`ModTileDirtyURL On`. It implements #272. I am not opposed to “default on” (which is the current behaviour)

I am very rust with C, so I highly encourage anyone to look at this and tell me if I'm doing something very wrong. I am in the early stages of testing this patch in production, so I suggest not merging it today.

### CODE REVIEW

**Comment by amandasaurus** [comment]
In Geofabrik we have been using this without issues for a while. Does anyone with better C/apache module experience want to provide feedback?

**Review by hummeltech — APPROVED** [review]
Awesome job, it looks great to me! I might suggest renaming the config options to `ModTileEnableStatusURL` & `ModTileEnableDirtyURL` and adding `enabled` to the function names though (similar to how `ModTileEnableStats` & `ModTileEnableTileThrottling` were implemented), to better represent their behavior.

**Comment by xamanu** [comment]
I am planning to release a new version within the upcoming weeks. @amandasaurus it would be great to get your improvements into this.

**Comment by amandasaurus** [comment]
Thank you for the reminder! I must have missed this notification¹. I've made those changes as requested. 🙂

---
¹ It's OK to remind me regularly if you don't hear any response (e.g., by commenting here asking for an update). I won't be offended and it will ensure I won't forget.

**Comment by xamanu** [comment]
Thanks a lot! Can you check the tiny liniting error please.

**Comment by amandasaurus** [comment]
On Mon, 06 Mar 2023 15:20 +01:00, Hummeltech ***@***.***> wrote:
>  I see the newly merged `CMake` 
> tests 
> <https://github.com/openstreetmap/mod_tile/actions/runs/4341352987> are 
> now failing on this pull request. This is caused by the breaking change 
> in b1393eb 
> <https://github.com/openstreetmap/mod_tile/commit/b1393ebe54de9b0e95406a771efca4f8f18077b9>, 
> to fix it just enable `ModTileEnableDirtyURL` & 
> `ModTileEnableStatusURL` in the test httpd.conf file 
> <https://github.com/amandasaurus/mod_tile/blob/status-and-dirty-conf-able/tests/httpd.conf.in#L17-L37> 

Yes I've been looking at that today. However I don't really know how C++/cmake/C/apache/Github actions work. I've no experience with this type of testing.

Do you have any sort of guide on how I can run that myself? I'd like to fix the tests.

-- 
Amanda

**Comment by hummeltech** [comment]
Hello @amandasaurus, sure thing. Sorry for the "construction", the updates to the `documentation` have not yet been merged in, so the repository is currently in somewhat of a mismatched state. You can take a look at https://github.com/openstreetmap/mod_tile/pull/311 to help you get the new testing system up and running.

You are probably interested in one of the `.md` files in [here](https://github.com/hummeltech/mod_tile/tree/master/docs/build), e.g. [ubuntu CMake build documentation](https://github.com/hummeltech/mod_tile/blob/master/docs/build/building_on_ubuntu.md)

**Comment by hummeltech** [comment]
Hello @amandasaurus, the build documentation has been updated not too long ago, [here is a link to the Ubuntu build doc](https://github.com/openstreetmap/mod_tile/blob/master/docs/build/building_on_ubuntu.md#ubuntu-20042204) which hopefully addresses your query.

Also, I have rebased your branch, pushed it up [here](https://github.com/openstreetmap/mod_tile/compare/master...status-and-dirty-conf-able) and tested it out (as well as changing the defaults to `On` rather than `Off` for backwards compatibility reasons.) If you have any changes you'd like to make, feel free to add some commits to this pull request, otherwise I will be merging the branch mentioned above in a week or so.

Thank you very much for your contribution!

**Comment by hummeltech** [comment]
Thanks again for the amazing work @amandasaurus! I am closing this and merging the newly created duplicate, #359.

**Pull request closed without merging**
