### PR TITLE
Make render_list reconnect if the renderd connection is lost

### PR DESCRIPTION
**Pull request by xamanu**
Rerolled https://github.com/openstreetmap/mod_tile/pull/128 by @tomhughes on the latest codebase.

This is up for testing.

### CODE REVIEW

**Comment by xamanu** [comment]
Added this for testing purposes to a release candidate for version 0.6 (https://github.com/openstreetmap/mod_tile/issues/227). See the issue for debian packages and please help testing.

**Comment by xamanu** [comment]
Applied it and had no issues, ready to become part of the next release candidate.

**Review by ldeffenb — COMMENTED** [review]
I notice that this doesn't retry the cmd that failed?

**Comment by tomhughes** [comment]
Yes I realised that recently but then forgot about it again... I've opened #240 to fix it.

**Pull request merged**
