### PR TITLE
Reduce redundant CI configuration by using local actions

### PR DESCRIPTION
**Pull request by hummeltech**
Also add compression to build archives to save time and drive space.

### CODE REVIEW

**Comment by xamanu** [comment]
It seems to take a minute longer than before (see [actions page](https://github.com/openstreetmap/mod_tile/actions). But anyway, this looks nice and well structured. I would bring this in. Shall we do as it is? Or do you have any idea on how to speed this up?

**Comment by hummeltech** [comment]
Ahh, perhaps it's the compression level, I've put it down to the default level.

**Comment by xamanu** [comment]
Yes, that made a small difference. This looks good to be merged. Thanks a lot!

**Comment by xamanu** [comment]
Can you please squash the two commits into one before i merge?

**Comment by hummeltech** [comment]
Yeah, that high compression takes a little longer and only saves a few megabytes (from 109MB to 12.7MB) more than the default compression level, which still does a fair job (from 109MB to 16MB)

**Pull request merged**
