### PR TITLE
Adhere to FHS 3.0 and use daemon under /run.

### PR DESCRIPTION
**Pull request by xamanu**
Reference: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html

### CODE REVIEW

**Comment by julienfastre** [comment]
I am probably wrong, but I had issues with starting renderd because the directory `/var/run/renderd` did not exists). I had to create it manually and then start renderd. Now, I create a systemd service definition which creates this directory with correct permissions on startup (my template below). 

Maybe we should somewhere have an explanation or a systemd definition to avoid this problem. (Unless this is the role of the packaging  to maintain this file ?).

```
[Unit]
Description=Renderd
After=network.target auditd.service

[Service]
User=gis
Group=gis
Type=simple
RuntimeDirectory=./renderd
RuntimeDirectoryMode=0755
Restart=always
ExecStart=/usr/local/bin/renderd --foreground -c /etc/renderd.conf

[Install]
WantedBy=multi-user.target
```

**Comment by xamanu** [comment]
It is a grey area :smile:

In principle I would say, if you compile it, `mod_tile` upstream here is the place for the adequate `systemd` configuration. If you create the Debian/Ubuntu package, then the packaging should assure that the `systemd` daemon works in this environment.

Currently `systemd` isn't included in the `mod_tile` main branch, but there are a couple of PRs in the pipeline (#75 and #154).

If you want to compare, for the current building of the Debian packages I use the [following `systemd` configuration](https://salsa.debian.org/debian-gis-team/libapache2-mod-tile/-/blob/master/debian/renderd.service). We also handle the daemon encapsulated in its own user.

The issue you are facing, it occurred to me, too. But as far as I saw, it was related to configuration issues.

Coming back to the initial statement, the problem you are facing is going to be addressed in the packaging effort. If there were problems, this would be a bug to be fixed by the package maintainer (me).

Please be aware that this PR is explicitly about changing the route of the daemon. Your input seems to be more related to the open PRs mentioned above.

**Comment by cquest** [comment]
Got the same problem with missing /var/run/renderd and more or less the same fix with systemd.

**Comment by julienfastre** [comment]
Thanks @xamanu. It seems correct for me to create the `/run/renderd` directory in the package, and let people who want to compile `renderd` themselve create it with their own method.

**Comment by xamanu** [comment]
@johanhenselmans can you please point me to the parts that need adjustments to work properly on FreeBSD? (Assuming this from the input in #216) Thanks

**Pull request merged**
