### PR TITLE
Fix installation when using DESTDIR.

### PR DESCRIPTION
**Pull request by sebastic**
The Debian package build failed after switching to CMake because it uses `DESTDIR` to install under `debian/tmp`.

### CODE REVIEW

**Comment by hummeltech** [comment]
Thank you for the pull request, I have also tried using relative paths (as per [CMake's recommendation](https://cmake.org/cmake/help/latest/command/install.html#id3)) but was never able to get everything to install to where I expected.

Are you using a prefix as well when generating the project buildsystem (I.E. `--install-prefix` or `CMAKE_INSTALL_PREFIX`)?

I currently do have some tests running using Docker which do use `DESTDIR` and it seems to work as expected in my experience. 

* Here is an example of it running with `DESTDIR=/tmp/mod_tile` and `CMAKE_INSTALL_PREFIX=/usr`
  * With absolute path:
    * Installs `renderd.conf` to `/tmp/mod_tile/etc/renderd.conf`
    * https://github.com/openstreetmap/mod_tile/actions/runs/8260157407/job/22595204449#step:3:4158
  * With relative path (from this pull request):
    * Installs `renderd.conf` to `/tmp/mod_tile/usr/etc/renderd.conf`
    * https://github.com/openstreetmap/mod_tile/actions/runs/8307036047/job/22739523290#step:3:4154

I would really love to get this working as well.

**Comment by sebastic** [comment]
See the Debian package build log:

 https://buildd.debian.org/status/fetch.php?pkg=libapache2-mod-tile&arch=amd64&ver=0.7.0-2&stamp=1710599274&raw=0

Formatted for readability:
> ```
> dh_auto_configure -- -DENABLE_TESTS:BOOL=ON
>     cd obj-x86_64-linux-gnu && \ 
>     DEB_PYTHON_INSTALL_LAYOUT=deb cmake -DCMAKE_INSTALL_PREFIX=/usr \ 
>                                         -DCMAKE_BUILD_TYPE=None \ 
>                                         -DCMAKE_INSTALL_SYSCONFDIR=/etc \ 
>                                         -DCMAKE_INSTALL_LOCALSTATEDIR=/var \ 
>                                         -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON \ 
>                                         -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF \ 
>                                         -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON \ 
>                                         -DFETCHCONTENT_FULLY_DISCONNECTED=ON \ 
>                                         -DCMAKE_INSTALL_RUNSTATEDIR=/run \ 
>                                         -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" \ 
>                                         -DCMAKE_VERBOSE_MAKEFILE=ON \ 
>                                         -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu \ 
>                                         -DENABLE_TESTS:BOOL=ON ..
> [...]
> dh_auto_install -a -O--buildsystem=cmake
>     cd obj-x86_64-linux-gnu && make -j6 install \
>                                         DESTDIR=/<<PKGBUILDDIR>>/debian/tmp \
>                                         AM_UPDATE_INFO_DIR=no \
>                                         "INSTALL=install --strip-program=true"
> ```

**Comment by hummeltech** [comment]
Thank you for the link, it does appear to be installing into the expected location, unless I'm not looking in the right place or the output in this link already has the patch applied.

`DESTDIR=/<<PKGBUILDDIR>>/debian/tmp` & `CMAKE_INSTALL_PREFIX=/usr`
```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "None"
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/var/cache/renderd/tiles
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/run/renderd
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/etc/apache2/mods-available/tile.load
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/etc/renderd.conf
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/lib/apache2/modules/mod_tile.so
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/bin/render_expired
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/bin/render_list
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/bin/render_old
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/bin/render_speedtest
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/bin/renderd
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man1/render_expired.1
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man1/render_list.1
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man1/render_old.1
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man1/render_speedtest.1
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man1/renderd.1
-- Installing: /<<PKGBUILDDIR>>/debian/tmp/usr/share/man/man5/renderd.conf.5
```

I do see that it is also overriding the default values for `CMAKE_INSTALL_SYSCONFDIR`, `CMAKE_INSTALL_LOCALSTATEDIR` and `CMAKE_INSTALL_RUNSTATEDIR` which might be solution I was looking for.

I will experiment with these values as well, I just want to get all of the tests passing.

Thanks!

**Comment by sebastic** [comment]
> Thank you for the link, it does appear to be installing into the expected location, unless I'm not looking in the right place or the output in this link already has the patch applied.

The patch is already applied, because it's required to make the package build successfully.

**Review by hummeltech — APPROVED** [review]

**Comment by hummeltech** [comment]
Thanks for the help! I'll merge this in and then create a follow up to adjust the documentation, Dockerfiles, etc.

**Comment by hummeltech** [comment]
Thanks again @sebastic! I have added this change into a new release (along with the documentation and required CI updates)
https://github.com/openstreetmap/mod_tile/releases/tag/v0.7.1

**Pull request merged**
