### PR TITLE
Allow tests to run again

### LINKED ISSUE #256: Problems with CI pipeline - `uses:` keyword is not currently supported.
We are facing issues with the CI pipeline, based on Github Actions. They fail with this error:

```
Error: `uses:` keyword is not currently supported.
```

We use `uses:` in our github actions definition. It worked before and is [part of the official documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses). @hummeltech, by chance do you know what is going on?

### PR DESCRIPTION
**Pull request by hummeltech**
FIxes #256

### CODE REVIEW

**Comment by xamanu** [comment]
yeay, thanks for getting us back on track. I see you avoid the `provision` actions. Can we remove them all together if they are not used?

**Comment by hummeltech** [comment]
Yes, that would be fine, I had left them in hoping that that functionality might be enabled soon, but I guess we can always just revert this change.

**Comment by xamanu** [comment]
Many thanks for this!

**Comment by xamanu** [comment]
Can you please squash the two commits? This would be nice. Thanks.

**Comment by hummeltech** [comment]
Alright, all done!

**Pull request merged**
