### PR TITLE
Test `CMake` build system support in `GitHub Actions`

### PR DESCRIPTION
**Pull request by hummeltech**
* Added `macOS` building & testing
* Added `FreeBSD` building & testing
* Added new `Linux` distributions for building & testing
  * `debian:testing` (`TBA`)
  * `fedora:36` (Released `2022-05-10`)
  * `fedora:37` (Released `2022-11-15`)
  * `fedora:rawhide` (`TBA`)
  * `ubuntu:22.04` (Released `2022-04-21`)
* Removed EOLed `Linux` distributions for building & testing
  * `fedora:33` (EOLed `2021-12-01`)
  * `fedora:34` (EOLed `2022-06-01`)
* The existing `Autotools` build system will still be tested on `Ubuntu 22.04` & `macOS 12`
* Coverage is enabled for `CMake`/`GNU` builds
* `LLVM` (`clang`) building & testing is enabled on `FreeBSD`, `macOS` & `Ubuntu 22.04`
---
[Here's an example](https://github.com/hummeltech/mod_tile/actions/runs/4310290680) of building & testing when on the `master` branch (or on `develop`).

### CODE REVIEW

**Comment by xamanu** [comment]
This is great. We need some testing, and then I am all in favour of bringing this in.

**Comment by xamanu** [comment]
In order to keep things clean, I would prefer not to include the following builds:
* `almalinux`
* `amazonlinux`
* `rockylinux`

Totally love that you are updating the version of the existing ones (`Fedora`, `Ubuntu`, and `Debian) and include `FreeBSD` and `macOS`.

**Comment by hummeltech** [comment]
@xamanu Sure thing, I removed them from the build matrix!

**Comment by hummeltech** [comment]
Alright @xamanu, I think this is ready too. I've also created a [Docker-based build pipeline](https://github.com/hummeltech/mod_tile/actions/runs/4271394180) that can also be used to test/demonstrate locally. I would like to follow this up with a docs update as well.

**Comment by xamanu** [comment]
Great. Please reroll with latest `master` which includes the cmake build system.

**Comment by hummeltech** [comment]
Alright @xamanu, this should be ready for review now. I needed to make a few minor changes to the `CMake` configuration to allow for building `mod_tile` with the `Mapnik >= 4` using `CMake`.

**Pull request merged**
